name: dao
services:

  postgresdb:
    image: postgres:16-alpine
    container_name: db-dao
    restart: always
    mem_limit: 1G
    env_file:
      - .env
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ../.data/db:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U test_user -d inventory_test"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
